[package]
name = "hola_scarb"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
quaireaux_math = { git = "https://github.com/keep-starknet-strange/quaireaux.git", rev = "4c93251" }

[scripts]
test = "cairo-test ."
